# Site settings
title: ruxubook
email: ruixin.xu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  问渠哪得清如许 唯有源头活水来
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ruxubook.com" # the base hostname & protocol for your site
#twitter_username: 
github_username:  ruixinxu

# Build settings
markdown: kramdown
